In [2]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  95  68  69  51  85
7   謝欣蓉  女  50  62  74  78  61
8   羅淑芬  女  82  66  63  97  54
9   許美慧  女  67  71  54  77  55
10  廖志豪  男  54  74  93  58  81

In [5]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
7   謝欣蓉  女  50  62  74  78  61
24  呂佳瑩  女  57  67  63  98  83
25  洪怡君  女  56  72  99  83  64
32  蕭怡伶  女  53  50  59  62  79
39  彭美慧  女  52  84  82  89  93
40  劉靜芬  女  51  59  65  81  54

In [6]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文  數學   地理  歷史   總分    平均    排名
42  邱裕豪  男   91  75  96   99  91  452  90.4   1.0
15  王婉茹  女   81  83  92   99  94  449  89.8   2.0
38  邱宗翰  男   90  77  99   88  94  448  89.6   3.0
22  李柏融  男   80  89  68   90  97  424  84.8   4.0
33  洪裕豪  男   87  70  88   81  94  420  84.0   5.0
23  曾明軒  男   72  91  78   76  95  412  82.4   6.0
50  詹柏翰  男   80  87  91   70  81  409  81.8   7.0
29  簡婉慧  女   68  62  88   90  98  406  81.2   8.0
46  鍾浩銘  男   93  93  76   77  67  406  81.2   8.0
37  呂怡靜  女   98  66  64  100  75  403  80.6  10.0
17  黃裕傑  男   84  73  99   81  64  401  80.2  11.0
39  彭美慧  女   52  84  82   89  93  400  80.0  12.0
12  呂承恩  男   65  68  90   73  99  395  79.0  13.0
21  蘇彥宏  男   81  75  89   93  55  393  78.6  14.0
31  曾靜儀  女   74  73  61   93  92  393  78.6  14.0
4   蕭志明  男   66  54  89   93  90  392  78.4  16.0
48  劉婉婷  女   73  99  95   54  68  389  77.8  17.0
20  莊子謙  男   91  93  94   60  51  389  77.8  17.0
13  蘇雅婷  女   99  80  62   56  92  389  77.8  17.0
34  簡建宏  男   70  67  68   92  90  387  77.4  20.0
43  吳雅萍  女   79  78  73   63  89  382  76.4  21.0
36  蕭浩宇  男   72  64  83   91  69  379  75.8  22.0
1   劉彥宏  男   87  62  76   63  90  378  75.6  23.0
18  王冠廷  男  100  78  65   81  54  378  75.6  23.0
5   王文傑  男   62  97  82   72  63  376  75.2  25.0
25  洪怡君  女   56  72  99   83  64  374  74.8  26.0
11  葉柏翰  男   97  73  91   50  61  372  74.4  27.0
6   朱冠霖  男   95  68  69   51  85  368  73.6  28.0
28  郭怡萱  女   97  95  55   66  55  368  73.6  28.0
24  呂佳瑩  女   57  67  63   98  83  368  73.6  28.0
26  洪柏宏  男   75  88  62   64  79  368  73.6  28.0
47  周美玲  女   74  72  74   75  68  363  72.6  32.0
41  許淑芬  女   89  59  64   85  65  362  72.4  33.0
8   羅淑芬  女   82  66  63   97  54  362  72.4  33.0
10  廖志豪  男   54  74  93   58  81  360  72.0  35.0
27  江雅琪  女   74  52  73   73  85  357  71.4  36.0
30  楊靜宜  女   87  51  84   53  81  356  71.2  37.0
19  呂婉慧  女   68  88  74   67  57  354  70.8  38.0
16  莊承翰  男   56  80  76   58  80  350  70.0  39.0
14  高浩宇  男   84  67  50   86  62  349  69.8  40.0
2   曾彥廷  男   56  68  56   84  84  348  69.6  41.0
35  劉浩然  男   56  82  63   88  59  348  69.6  41.0
49  曾明哲  男   60  87  70   67  60  344  68.8  43.0
45  莊柏融  男   55  71  97   56  54  333  66.6  44.0
44  施子軒  男   54  62  68   56  87  327  65.4  45.0
7   謝欣蓉  女   50  62  74   78  61  325  65.0  46.0
9   許美慧  女   67  71  54   77  55  324  64.8  47.0
40  劉靜芬  女   51  59  65   81  54  310  62.0  48.0
32  蕭怡伶  女   53  50  59   62  79  303  60.6  49.0
3   吳子睿  男   52  60  67   50  55  284  56.8  50.0