In [1]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1   -1.404191
   2   -0.264228
   3    0.042534
b  1    0.179097
   2   -1.392536
c  3    1.088354
   1    0.156074
d  2    1.698921
   3   -0.905571
dtype: float64

In [2]:
data1 = data.unstack()
data1

          1         2         3
a -1.404191 -0.264228  0.042534
b  0.179097 -1.392536       NaN
c  0.156074       NaN  1.088354
d       NaN  1.698921 -0.905571

In [3]:
data1.stack()

a  1   -1.404191
   2   -0.264228
   3    0.042534
b  1    0.179097
   2   -1.392536
   3         NaN
c  1    0.156074
   2         NaN
   3    1.088354
d  1         NaN
   2    1.698921
   3   -0.905571
dtype: float64

In [4]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [5]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [6]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10

In [7]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.288360 -0.511743
1    a  two -0.043891  0.415421
2    b  one  0.731318 -0.038229
3    b  two -0.460595  0.460339
4    a  one  0.064894 -0.782006